"""Tool declarations, registry, and the single execution gateway."""

from ..guardrails import GuardrailManager
from .catalog import (
    FILE_READ,
    FORWARD_SCENE_SEND,
    GROUP_GET_MEMBERS,
    GROUP_GET_RANDOM_MEMBER,
    GROUP_GET_RECENT_SPEAKERS,
    GROUP_KICK_MEMBER,
    GROUP_MUTE_MEMBER,
    GROUP_UNMUTE_MEMBER,
    MEMORY_FORGET,
    MEMORY_RECALL,
    MEMORY_REMEMBER,
    MESSAGE_GET_RECENT_FOR_RECALL,
    MESSAGE_RECALL,
    MESSAGE_SEND,
    MODEL_RATINGS,
    REMINDER_CANCEL,
    REMINDER_CREATE,
    REMINDER_LIST,
    REMINDER_PAUSE,
    REMINDER_RESUME,
    STICKER_CONSIDER,
    STICKER_DELETE,
    STICKER_LIST,
    STICKER_SEARCH,
    STICKER_SEND,
    TOKEN_CALCULATE,
    TOOL_CATALOG,
    WEB_FETCH,
)
from .gateway import ToolGateway
from .models import (
    ParameterSpec,
    ParameterType,
    ToolContext,
    ToolDefinition,
    ToolHandler,
    ToolResult,
    ToolResultCode,
    ToolRisk,
    validate_parameters,
)
from .onebot import OneBotActionClient, OneBotToolRuntime, resolve_event_action_client
from .registry import RegisteredTool, ToolRegistrationError, ToolRegistry

__all__ = [
    "ParameterSpec",
    "ParameterType",
    "GROUP_GET_MEMBERS",
    "GROUP_GET_RECENT_SPEAKERS",
    "GROUP_GET_RANDOM_MEMBER",
    "GROUP_KICK_MEMBER",
    "GROUP_MUTE_MEMBER",
    "GROUP_UNMUTE_MEMBER",
    "FORWARD_SCENE_SEND",
    "FILE_READ",
    "MESSAGE_GET_RECENT_FOR_RECALL",
    "MESSAGE_RECALL",
    "MESSAGE_SEND",
    "MEMORY_FORGET",
    "MEMORY_RECALL",
    "MEMORY_REMEMBER",
    "MODEL_RATINGS",
    "TOKEN_CALCULATE",
    "REMINDER_CANCEL",
    "REMINDER_CREATE",
    "REMINDER_LIST",
    "REMINDER_PAUSE",
    "REMINDER_RESUME",
    "WEB_FETCH",
    "STICKER_CONSIDER",
    "STICKER_DELETE",
    "STICKER_LIST",
    "STICKER_SEARCH",
    "STICKER_SEND",
    "RegisteredTool",
    "ToolContext",
    "ToolDefinition",
    "ToolGateway",
    "GuardrailManager",
    "ToolHandler",
    "ToolRegistrationError",
    "ToolRegistry",
    "OneBotActionClient",
    "OneBotToolRuntime",
    "ToolResult",
    "ToolResultCode",
    "ToolRisk",
    "TOOL_CATALOG",
    "validate_parameters",
    "resolve_event_action_client",
]
